# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Secret="!Hello918273645World!"
      - Issuer="QGT-AuthService"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
