name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker build . --file taxabooking-svc/Dockerfile --tag ${DOCKER_USER}/taxabooking-svc:latest
    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker push ${DOCKER_USER}/taxabooking-svc:latest
